#
# * SQL Localization script - Translate countries
# * @package Installer
# * @access private
# * @copyright Copyright 2004-2009 Andrew Berezin eCommerce-Service.com
# * @copyright Copyright 2003-2009 Zen Cart Development Team
# * @copyright Portions Copyright 2003 osCommerce
# * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
# * @Localization: Andrew Berezin http://ecommerce-service.com
# * @version $Id: mysql_50_translate_countries.sql 1.3.8a 17.12.2007 11:02 AndrewBerezin $

## http://www.iso.org/iso/en/prods-services/iso3166ma/02iso-3166-code-lists/list-en1.html
## http://www.magnum-opus.ru/wiki/ISO-3166-1
UPDATE countries SET countries_name='Афганистан' WHERE countries_iso_code_3='AFG';
UPDATE countries SET countries_name='Албания' WHERE countries_iso_code_3='ALB';
UPDATE countries SET countries_name='Алжир' WHERE countries_iso_code_3='DZA';
UPDATE countries SET countries_name='Американский Самоа' WHERE countries_iso_code_3='ASM';
UPDATE countries SET countries_name='Андорра' WHERE countries_iso_code_3='AND';
UPDATE countries SET countries_name='Ангола' WHERE countries_iso_code_3='AGO';
UPDATE countries SET countries_name='Ангилья' WHERE countries_iso_code_3='AIA';
UPDATE countries SET countries_name='Антарктика' WHERE countries_iso_code_3='ATA';
UPDATE countries SET countries_name='Антигуа и Барбуда' WHERE countries_iso_code_3='ATG';
UPDATE countries SET countries_name='Аргентина' WHERE countries_iso_code_3='ARG';
UPDATE countries SET countries_name='Армения' WHERE countries_iso_code_3='ARM';
UPDATE countries SET countries_name='Аруба' WHERE countries_iso_code_3='ABW';
UPDATE countries SET countries_name='Австралия' WHERE countries_iso_code_3='AUS';
UPDATE countries SET countries_name='Австрия' WHERE countries_iso_code_3='AUT';
UPDATE countries SET countries_name='Азербайджан' WHERE countries_iso_code_3='AZE';
UPDATE countries SET countries_name='Багамские острова' WHERE countries_iso_code_3='BHS';
UPDATE countries SET countries_name='Бахрейн' WHERE countries_iso_code_3='BHR';
UPDATE countries SET countries_name='Бангладеш' WHERE countries_iso_code_3='BGD';
UPDATE countries SET countries_name='Барбадос' WHERE countries_iso_code_3='BRB';
UPDATE countries SET countries_name='Беларусь' WHERE countries_iso_code_3='BLR';
UPDATE countries SET countries_name='Бельгия' WHERE countries_iso_code_3='BEL';
UPDATE countries SET countries_name='Белиз' WHERE countries_iso_code_3='BLZ';
UPDATE countries SET countries_name='Бенин' WHERE countries_iso_code_3='BEN';
UPDATE countries SET countries_name='Бермуды' WHERE countries_iso_code_3='BMU';
UPDATE countries SET countries_name='Бутан' WHERE countries_iso_code_3='BTN';
UPDATE countries SET countries_name='Боливия' WHERE countries_iso_code_3='BOL';
UPDATE countries SET countries_name='Босния и Герцеговина' WHERE countries_iso_code_3='BIH';
UPDATE countries SET countries_name='Ботсвана' WHERE countries_iso_code_3='BWA';
UPDATE countries SET countries_name='остров Буве' WHERE countries_iso_code_3='BVT';
UPDATE countries SET countries_name='Бразилия' WHERE countries_iso_code_3='BRA';
UPDATE countries SET countries_name='Британские территории Индийского океана' WHERE countries_iso_code_3='IOT';
UPDATE countries SET countries_name='Бруней' WHERE countries_iso_code_3='BRN';
UPDATE countries SET countries_name='Болгария' WHERE countries_iso_code_3='BGR';
UPDATE countries SET countries_name='Буркина Фасо' WHERE countries_iso_code_3='BFA';
UPDATE countries SET countries_name='Бурунди' WHERE countries_iso_code_3='BDI';
UPDATE countries SET countries_name='Камбоджа' WHERE countries_iso_code_3='KHM';
UPDATE countries SET countries_name='Камерун' WHERE countries_iso_code_3='CMR';
UPDATE countries SET countries_name='Канада' WHERE countries_iso_code_3='CAN';
UPDATE countries SET countries_name='острова Зеленого Мыса' WHERE countries_iso_code_3='CPV';
UPDATE countries SET countries_name='Каймановы острова' WHERE countries_iso_code_3='CYM';
UPDATE countries SET countries_name='Центральная Африканская Республика' WHERE countries_iso_code_3='CAF';
UPDATE countries SET countries_name='Чад' WHERE countries_iso_code_3='TCD';
UPDATE countries SET countries_name='Чили' WHERE countries_iso_code_3='CHL';
UPDATE countries SET countries_name='Китайская Народная Республика' WHERE countries_iso_code_3='CHN';
UPDATE countries SET countries_name='остров Рождества' WHERE countries_iso_code_3='CXR';
UPDATE countries SET countries_name='Кокосовые острова' WHERE countries_iso_code_3='CCK';
UPDATE countries SET countries_name='Колумбия' WHERE countries_iso_code_3='COL';
UPDATE countries SET countries_name='Коморские острова' WHERE countries_iso_code_3='COM';
UPDATE countries SET countries_name='Конго' WHERE countries_iso_code_3='COG';
UPDATE countries SET countries_name='острова Кука' WHERE countries_iso_code_3='COK';
UPDATE countries SET countries_name='Коста Рика' WHERE countries_iso_code_3='CRI';
UPDATE countries SET countries_name='Кот-д''Ивуар' WHERE countries_iso_code_3='CIV';
UPDATE countries SET countries_name='Хорватия' WHERE countries_iso_code_3='HRV';
UPDATE countries SET countries_name='Куба' WHERE countries_iso_code_3='CUB';
UPDATE countries SET countries_name='Кипр' WHERE countries_iso_code_3='CYP';
UPDATE countries SET countries_name='Чехия' WHERE countries_iso_code_3='CZE';
UPDATE countries SET countries_name='Дания' WHERE countries_iso_code_3='DNK';
UPDATE countries SET countries_name='Джибути' WHERE countries_iso_code_3='DJI';
UPDATE countries SET countries_name='Доминика' WHERE countries_iso_code_3='DMA';
UPDATE countries SET countries_name='Доминиканская республика' WHERE countries_iso_code_3='DOM';
UPDATE countries SET countries_name='Восточный Тимур' WHERE countries_iso_code_3='TMP';
UPDATE countries SET countries_name='Эквадор' WHERE countries_iso_code_3='ECU';
UPDATE countries SET countries_name='Египет' WHERE countries_iso_code_3='EGY';
UPDATE countries SET countries_name='Сальвадор' WHERE countries_iso_code_3='SLV';
UPDATE countries SET countries_name='Экваториальная Гвинея' WHERE countries_iso_code_3='GNQ';
UPDATE countries SET countries_name='Эритрея' WHERE countries_iso_code_3='ERI';
UPDATE countries SET countries_name='Эстония' WHERE countries_iso_code_3='EST';
UPDATE countries SET countries_name='Эфиопия' WHERE countries_iso_code_3='ETH';
UPDATE countries SET countries_name='Фолклендские' WHERE countries_iso_code_3='FLK';
UPDATE countries SET countries_name='Фарерские острова' WHERE countries_iso_code_3='FRO';
UPDATE countries SET countries_name='Фиджи' WHERE countries_iso_code_3='FJI';
UPDATE countries SET countries_name='Финляндия' WHERE countries_iso_code_3='FIN';
UPDATE countries SET countries_name='Франция' WHERE countries_iso_code_3='FRA';
UPDATE countries SET countries_name='Франция, Метрополия' WHERE countries_iso_code_3='FXX';
UPDATE countries SET countries_name='Французская Гвиана' WHERE countries_iso_code_3='GUF';
UPDATE countries SET countries_name='Французская Полинезия' WHERE countries_iso_code_3='PYF';
UPDATE countries SET countries_name='Французские Южные Территории' WHERE countries_iso_code_3='ATF';
UPDATE countries SET countries_name='Габон' WHERE countries_iso_code_3='GAB';
UPDATE countries SET countries_name='Гамбия' WHERE countries_iso_code_3='GMB';
UPDATE countries SET countries_name='Грузия' WHERE countries_iso_code_3='GEO';
UPDATE countries SET countries_name='Германия' WHERE countries_iso_code_3='DEU';
UPDATE countries SET countries_name='Гана' WHERE countries_iso_code_3='GHA';
UPDATE countries SET countries_name='Гибралтар' WHERE countries_iso_code_3='GIB';
UPDATE countries SET countries_name='Греция' WHERE countries_iso_code_3='GRC';
UPDATE countries SET countries_name='Гренландия' WHERE countries_iso_code_3='GRL';
UPDATE countries SET countries_name='Гренада' WHERE countries_iso_code_3='GRD';
UPDATE countries SET countries_name='Гваделупа' WHERE countries_iso_code_3='GLP';
UPDATE countries SET countries_name='Гуам' WHERE countries_iso_code_3='GUM';
UPDATE countries SET countries_name='Гватемала' WHERE countries_iso_code_3='GTM';
UPDATE countries SET countries_name='Гвинея' WHERE countries_iso_code_3='GIN';
UPDATE countries SET countries_name='Гвинея-Бисау' WHERE countries_iso_code_3='GNB';
UPDATE countries SET countries_name='Гайана' WHERE countries_iso_code_3='GUY';
UPDATE countries SET countries_name='Гаити' WHERE countries_iso_code_3='HTI';
UPDATE countries SET countries_name='острова Герда и МакДональда' WHERE countries_iso_code_3='HMD';
UPDATE countries SET countries_name='Гондурас' WHERE countries_iso_code_3='HND';
UPDATE countries SET countries_name='Гонконг' WHERE countries_iso_code_3='HKG';
UPDATE countries SET countries_name='Венгрия' WHERE countries_iso_code_3='HUN';
UPDATE countries SET countries_name='Исландия' WHERE countries_iso_code_3='ISL';
UPDATE countries SET countries_name='Индия' WHERE countries_iso_code_3='IND';
UPDATE countries SET countries_name='Индонезия' WHERE countries_iso_code_3='IDN';
UPDATE countries SET countries_name='Иран' WHERE countries_iso_code_3='IRN';
UPDATE countries SET countries_name='Ирак' WHERE countries_iso_code_3='IRQ';
UPDATE countries SET countries_name='Ирландия' WHERE countries_iso_code_3='IRL';
UPDATE countries SET countries_name='Израиль' WHERE countries_iso_code_3='ISR';
UPDATE countries SET countries_name='Италия' WHERE countries_iso_code_3='ITA';
UPDATE countries SET countries_name='Ямайка' WHERE countries_iso_code_3='JAM';
UPDATE countries SET countries_name='Япония' WHERE countries_iso_code_3='JPN';
UPDATE countries SET countries_name='Иордания' WHERE countries_iso_code_3='JOR';
UPDATE countries SET countries_name='Казахстан' WHERE countries_iso_code_3='KAZ';
UPDATE countries SET countries_name='Кения' WHERE countries_iso_code_3='KEN';
UPDATE countries SET countries_name='Кирибати' WHERE countries_iso_code_3='KIR';
UPDATE countries SET countries_name='Корейская Народная Демократическая республика' WHERE countries_iso_code_3='PRK';
UPDATE countries SET countries_name='Корея' WHERE countries_iso_code_3='KOR';
UPDATE countries SET countries_name='Кувейт' WHERE countries_iso_code_3='KWT';
UPDATE countries SET countries_name='Кыргызстан' WHERE countries_iso_code_3='KGZ';
UPDATE countries SET countries_name='Лаос' WHERE countries_iso_code_3='LAO';
UPDATE countries SET countries_name='Латвия' WHERE countries_iso_code_3='LVA';
UPDATE countries SET countries_name='Ливан' WHERE countries_iso_code_3='LBN';
UPDATE countries SET countries_name='Лесото' WHERE countries_iso_code_3='LSO';
UPDATE countries SET countries_name='Либерия' WHERE countries_iso_code_3='LBR';
UPDATE countries SET countries_name='Ливия' WHERE countries_iso_code_3='LBY';
UPDATE countries SET countries_name='Лихтенштейн' WHERE countries_iso_code_3='LIE';
UPDATE countries SET countries_name='Литва' WHERE countries_iso_code_3='LTU';
UPDATE countries SET countries_name='Люксембург' WHERE countries_iso_code_3='LUX';
UPDATE countries SET countries_name='Макао' WHERE countries_iso_code_3='MAC';
UPDATE countries SET countries_name='Македония' WHERE countries_iso_code_3='MKD';
UPDATE countries SET countries_name='Мадагаскар' WHERE countries_iso_code_3='MDG';
UPDATE countries SET countries_name='Малави' WHERE countries_iso_code_3='MWI';
UPDATE countries SET countries_name='Малайзия' WHERE countries_iso_code_3='MYS';
UPDATE countries SET countries_name='Мальдивские острова' WHERE countries_iso_code_3='MDV';
UPDATE countries SET countries_name='Мали' WHERE countries_iso_code_3='MLI';
UPDATE countries SET countries_name='Мальта' WHERE countries_iso_code_3='MLT';
UPDATE countries SET countries_name='Маршалловы острова' WHERE countries_iso_code_3='MHL';
UPDATE countries SET countries_name='Мартиника' WHERE countries_iso_code_3='MTQ';
UPDATE countries SET countries_name='Мавритания' WHERE countries_iso_code_3='MRT';
UPDATE countries SET countries_name='Маврикий' WHERE countries_iso_code_3='MUS';
UPDATE countries SET countries_name='Майотта' WHERE countries_iso_code_3='MYT';
UPDATE countries SET countries_name='Мексика' WHERE countries_iso_code_3='MEX';
UPDATE countries SET countries_name='Микронезия' WHERE countries_iso_code_3='FSM';
UPDATE countries SET countries_name='Молдова' WHERE countries_iso_code_3='MDA';
UPDATE countries SET countries_name='Монако' WHERE countries_iso_code_3='MCO';
UPDATE countries SET countries_name='Монголия' WHERE countries_iso_code_3='MNG';
UPDATE countries SET countries_name='Монтсеррат' WHERE countries_iso_code_3='MSR';
UPDATE countries SET countries_name='Марокко' WHERE countries_iso_code_3='MAR';
UPDATE countries SET countries_name='Мозамбик' WHERE countries_iso_code_3='MOZ';
UPDATE countries SET countries_name='Мьянма' WHERE countries_iso_code_3='MMR';
UPDATE countries SET countries_name='Намибия' WHERE countries_iso_code_3='NAM';
UPDATE countries SET countries_name='Науру' WHERE countries_iso_code_3='NRU';
UPDATE countries SET countries_name='Непал' WHERE countries_iso_code_3='NPL';
UPDATE countries SET countries_name='Нидерланды' WHERE countries_iso_code_3='NLD';
UPDATE countries SET countries_name='Антильские острова' WHERE countries_iso_code_3='ANT';
UPDATE countries SET countries_name='Новая Каледония' WHERE countries_iso_code_3='NCL';
UPDATE countries SET countries_name='Новая Зеландия' WHERE countries_iso_code_3='NZL';
UPDATE countries SET countries_name='Никарагуа' WHERE countries_iso_code_3='NIC';
UPDATE countries SET countries_name='Нигер' WHERE countries_iso_code_3='NER';
UPDATE countries SET countries_name='Нигерия' WHERE countries_iso_code_3='NGA';
UPDATE countries SET countries_name='Ниуэ' WHERE countries_iso_code_3='NIU';
UPDATE countries SET countries_name='остров Норфолк' WHERE countries_iso_code_3='NFK';
UPDATE countries SET countries_name='Марианские острова' WHERE countries_iso_code_3='MNP';
UPDATE countries SET countries_name='Норвегия' WHERE countries_iso_code_3='NOR';
UPDATE countries SET countries_name='Оман' WHERE countries_iso_code_3='OMN';
UPDATE countries SET countries_name='Пакистан' WHERE countries_iso_code_3='PAK';
UPDATE countries SET countries_name='Палау' WHERE countries_iso_code_3='PLW';
UPDATE countries SET countries_name='Панама' WHERE countries_iso_code_3='PAN';
UPDATE countries SET countries_name='Папуа - Новая Гвинея' WHERE countries_iso_code_3='PNG';
UPDATE countries SET countries_name='Парагвай' WHERE countries_iso_code_3='PRY';
UPDATE countries SET countries_name='Перу' WHERE countries_iso_code_3='PER';
UPDATE countries SET countries_name='Филиппины' WHERE countries_iso_code_3='PHL';
UPDATE countries SET countries_name='остров Питкэрн' WHERE countries_iso_code_3='PCN';
UPDATE countries SET countries_name='Польша' WHERE countries_iso_code_3='POL';
UPDATE countries SET countries_name='Португалия' WHERE countries_iso_code_3='PRT';
UPDATE countries SET countries_name='Пуэрто-Рико' WHERE countries_iso_code_3='PRI';
UPDATE countries SET countries_name='Катар' WHERE countries_iso_code_3='QAT';
UPDATE countries SET countries_name='Реюньон' WHERE countries_iso_code_3='REU';
UPDATE countries SET countries_name='Румыния' WHERE countries_iso_code_3='ROM';
UPDATE countries SET countries_name='Россия' WHERE countries_iso_code_3='RUS';
UPDATE countries SET countries_name='Руанда' WHERE countries_iso_code_3='RWA';
UPDATE countries SET countries_name='Сент-Китс и Невис' WHERE countries_iso_code_3='KNA';
UPDATE countries SET countries_name='Сент-Люсия' WHERE countries_iso_code_3='LCA';
UPDATE countries SET countries_name='Сент-Винсент и Гренадины' WHERE countries_iso_code_3='VCT';
UPDATE countries SET countries_name='острова Самоа' WHERE countries_iso_code_3='WSM';
UPDATE countries SET countries_name='Сан-Марино' WHERE countries_iso_code_3='SMR';
UPDATE countries SET countries_name='Сан-Томе и Принсипи' WHERE countries_iso_code_3='STP';
UPDATE countries SET countries_name='Саудовская Аравия' WHERE countries_iso_code_3='SAU';
UPDATE countries SET countries_name='Сенегал' WHERE countries_iso_code_3='SEN';
UPDATE countries SET countries_name='Сейшельские острова' WHERE countries_iso_code_3='SYC';
UPDATE countries SET countries_name='Сьерра-Леоне' WHERE countries_iso_code_3='SLE';
UPDATE countries SET countries_name='Сингапур' WHERE countries_iso_code_3='SGP';
UPDATE countries SET countries_name='Словакия' WHERE countries_iso_code_3='SVK';
UPDATE countries SET countries_name='Словения' WHERE countries_iso_code_3='SVN';
UPDATE countries SET countries_name='Соломоновы острова' WHERE countries_iso_code_3='SLB';
UPDATE countries SET countries_name='Сомали' WHERE countries_iso_code_3='SOM';
UPDATE countries SET countries_name='ЮАР' WHERE countries_iso_code_3='ZAF';
UPDATE countries SET countries_name='Южная Георгия и Южные Сандвичевы острова' WHERE countries_iso_code_3='SGS';
UPDATE countries SET countries_name='Испания' WHERE countries_iso_code_3='ESP';
UPDATE countries SET countries_name='Шри Ланка' WHERE countries_iso_code_3='LKA';
UPDATE countries SET countries_name='остров Святой Елены' WHERE countries_iso_code_3='SHN';
UPDATE countries SET countries_name='Сен-Пьер и Микелон' WHERE countries_iso_code_3='SPM';
UPDATE countries SET countries_name='Судан' WHERE countries_iso_code_3='SDN';
UPDATE countries SET countries_name='Суринам' WHERE countries_iso_code_3='SUR';
UPDATE countries SET countries_name='острова Свалбард и Ян Майен' WHERE countries_iso_code_3='SJM';
UPDATE countries SET countries_name='Свазиленд' WHERE countries_iso_code_3='SWZ';
UPDATE countries SET countries_name='Швеция' WHERE countries_iso_code_3='SWE';
UPDATE countries SET countries_name='Швейцария' WHERE countries_iso_code_3='CHE';
UPDATE countries SET countries_name='Сирия' WHERE countries_iso_code_3='SYR';
UPDATE countries SET countries_name='Тайвань' WHERE countries_iso_code_3='TWN';
UPDATE countries SET countries_name='Таджикистан' WHERE countries_iso_code_3='TJK';
UPDATE countries SET countries_name='Танзания' WHERE countries_iso_code_3='TZA';
UPDATE countries SET countries_name='Тайланд' WHERE countries_iso_code_3='THA';
UPDATE countries SET countries_name='Того' WHERE countries_iso_code_3='TGO';
UPDATE countries SET countries_name='Токелау' WHERE countries_iso_code_3='TKL';
UPDATE countries SET countries_name='Тонга' WHERE countries_iso_code_3='TON';
UPDATE countries SET countries_name='Тринидад и Тобаго' WHERE countries_iso_code_3='TTO';
UPDATE countries SET countries_name='Тунис' WHERE countries_iso_code_3='TUN';
UPDATE countries SET countries_name='Турция' WHERE countries_iso_code_3='TUR';
UPDATE countries SET countries_name='Туркменистан' WHERE countries_iso_code_3='TKM';
UPDATE countries SET countries_name='острова Туркс и Кайкос' WHERE countries_iso_code_3='TCA';
UPDATE countries SET countries_name='Тувалу' WHERE countries_iso_code_3='TUV';
UPDATE countries SET countries_name='Уганда' WHERE countries_iso_code_3='UGA';
UPDATE countries SET countries_name='Украина' WHERE countries_iso_code_3='UKR';
UPDATE countries SET countries_name='Арабские Эмираты' WHERE countries_iso_code_3='ARE';
UPDATE countries SET countries_name='Великобритания' WHERE countries_iso_code_3='GBR';
UPDATE countries SET countries_name='Соединенные Штаты Америки' WHERE countries_iso_code_3='USA';
UPDATE countries SET countries_name='Отдаленные Острова США' WHERE countries_iso_code_3='UMI';
UPDATE countries SET countries_name='Уругвай' WHERE countries_iso_code_3='URY';
UPDATE countries SET countries_name='Узбекистан' WHERE countries_iso_code_3='UZB';
UPDATE countries SET countries_name='Вануату' WHERE countries_iso_code_3='VUT';
UPDATE countries SET countries_name='Ватикан' WHERE countries_iso_code_3='VAT';
UPDATE countries SET countries_name='Венесуэла' WHERE countries_iso_code_3='VEN';
UPDATE countries SET countries_name='Вьетнам' WHERE countries_iso_code_3='VNM';
UPDATE countries SET countries_name='Британские Виргинские острова' WHERE countries_iso_code_3='VGB';
UPDATE countries SET countries_name='Американские Виргинские острова' WHERE countries_iso_code_3='VIR';
UPDATE countries SET countries_name='острова Валлис и Футуна' WHERE countries_iso_code_3='WLF';
UPDATE countries SET countries_name='Западная Сахара' WHERE countries_iso_code_3='ESH';
UPDATE countries SET countries_name='Йемен' WHERE countries_iso_code_3='YEM';
UPDATE countries SET countries_name='Югославия' WHERE countries_iso_code_3='YUG';
UPDATE countries SET countries_name='Заир' WHERE countries_iso_code_3='ZAR';
UPDATE countries SET countries_name='Замбия' WHERE countries_iso_code_3='ZMB';
UPDATE countries SET countries_name='Зимбабве' WHERE countries_iso_code_3='ZWE';
UPDATE countries SET countries_name='Эландские Острова' WHERE countries_iso_code_3='ALA';