#
# * SQL Localization script - Prepare tables for Localization
# * @package Installer
# * @access private
# * @copyright Copyright 2004-2009 Andrew Berezin eCommerce-Service.com
# * @copyright Copyright 2003-2009 Zen Cart Development Team
# * @copyright Portions Copyright 2003 osCommerce
# * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
# * @Localization: Andrew Berezin http://ecommerce-service.com
# * @version $Id: mysql_00_alter_tables.sql 1.3.8a 17.12.2007 11:21 AndrewBerezin $

ALTER TABLE address_book CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE address_book DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE address_format CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE address_format DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE admin CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE admin DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE admin_activity_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE admin_activity_log DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE authorizenet CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE authorizenet DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE banners CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE banners DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE banners_history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE banners_history DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE categories DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE categories_description CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE categories_description DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE configuration CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE configuration DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE configuration_group CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE configuration_group DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE counter CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE counter DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE counter_history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE counter_history DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE countries CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE countries DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_email_track CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_email_track DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_gv_customer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_gv_customer DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_gv_queue CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_gv_queue DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_redeem_track CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_redeem_track DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_restrict CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupon_restrict DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupons CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupons DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupons_description CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coupons_description DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE currencies CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE currencies DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_basket CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_basket DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_basket_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_basket_attributes DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_info DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_wishlist CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE customers_wishlist DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE db_cache CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE db_cache DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE email_archive CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE email_archive DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ezpages CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ezpages DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE featured CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE featured DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE files_uploaded CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE files_uploaded DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE geo_zones CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE geo_zones DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE get_terms_to_filter CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE get_terms_to_filter DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE group_pricing CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE group_pricing DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE languages CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE languages DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layout_boxes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layout_boxes DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE manufacturers CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE manufacturers DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE manufacturers_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE manufacturers_info DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_clips CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_clips DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_manager CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_manager DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_to_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_to_products DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_types CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE media_types DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE meta_tags_categories_description CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE meta_tags_categories_description DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE meta_tags_products_description CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE meta_tags_products_description DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE music_genre CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE music_genre DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE newsletters CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE newsletters DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE nochex_apc_transactions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE nochex_apc_transactions DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE nochex_sessions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE nochex_sessions DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_products DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_products_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_products_attributes DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_products_download CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_products_download DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_status CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_status DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_status_history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_status_history DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_total CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE orders_total DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_payment_status CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_payment_status DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_payment_status_history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_payment_status_history DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_session CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_session DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_testing CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE paypal_testing DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_music_extra CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_music_extra DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_type_layout CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_type_layout DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_types CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_types DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_types_to_category CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product_types_to_category DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_attributes DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_attributes_download CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_attributes_download DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_description CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_description DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_discount_quantity CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_discount_quantity DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_notifications CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_notifications DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options_types CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options_types DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options_values CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options_values DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options_values_to_products_options CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_options_values_to_products_options DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_to_categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE products_to_categories DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE project_version CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE project_version DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE project_version_history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE project_version_history DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE query_builder CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE query_builder DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_artists CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_artists DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_artists_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_artists_info DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_company CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_company DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_company_info CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE record_company_info DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE reviews CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE reviews DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE reviews_description CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE reviews_description DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE salemaker_sales CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE salemaker_sales DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sessions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sessions DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE specials CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE specials DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE tax_class CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE tax_class DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE tax_rates CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE tax_rates DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE template_select CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE template_select DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE upgrade_exceptions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE upgrade_exceptions DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE whos_online CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE whos_online DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zones CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zones DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zones_to_geo_zones CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zones_to_geo_zones DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
